version: 2.1

description: |
  Use Docker in your workflows.

executors:
  build:
    docker:
      - image: "jobteaser/circleci-docker-build:latest"
        auth:
          username: "$DOCKER_LOGIN"
          password: "$DOCKER_PASSWORD"

commands:
  setup:
    steps:
      - setup_remote_docker:
          docker_layer_caching: true

  login:
    steps:
      - run:
          name: "Login on the remote registry."
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin

  build_image:
    parameters:
      dockerfile_path:
        description: "The path of the dockerfile to build."
        type: string
        default: "Dockerfile"
      image_name:
        description: "The name of the image."
        type: string
        default: "jobteaser/$CIRCLE_PROJECT_REPONAME"
      image_tag:
        description: "The tag of the image."
        type: string
        default: "git-$CIRCLE_SHA1"
    steps:
      - run:
          name: "Build the image."
          command: |
            docker build -t <<parameters.image_name>>:<<parameters.image_tag>> \
                         -f <<parameters.dockerfile_path>> \
                         .

  push_image:
    parameters:
      image_name:
        description: "The name of the image."
        type: string
        default: "jobteaser/$CIRCLE_PROJECT_REPONAME"
      image_tag:
        description: "The tag of the image."
        type: string
        default: "git-$CIRCLE_SHA1"
    steps:
      - run:
          name: "Push the image to the remote registry."
          command: |
            docker push <<parameters.image_name>>:<<parameters.image_tag>>

jobs:
  build_image:
    parameters:
      dockerfile_path:
        description: "The path of the dockerfile to build."
        type: string
        default: "Dockerfile"
      image_name:
        description: "The name of the Docker image."
        type: string
        default: "jobteaser/$CIRCLE_PROJECT_REPONAME"
      image_tag:
        description: "The tag of the Docker image."
        type: string
        default: "git-$CIRCLE_SHA1"
    executor: "build"
    steps:
      - checkout
      - setup
      - login
      - build_image:
          dockerfile_path: "<<parameters.dockerfile_path>>"
          image_name: "<<parameters.image_name>>"
          image_tag: "<<parameters.image_tag>>"
      - push_image:
          image_name: "<<parameters.image_name>>"
          image_tag: "<<parameters.image_tag>>"
