version: 2.1

description: |
  Use Docker in your workflows.

executors:
  build:
    docker:
      - image: "jobteaser/circleci-docker-build:latest"
        auth:
          username: "$DOCKER_LOGIN"
          password: "$DOCKER_PASSWORD"

commands:
  setup:
    steps:
      - setup_remote_docker:
          docker_layer_caching: true

  login:
    steps:
      - run:
          name: "Login on the remote registry."
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin

  build_image:
    parameters:
      dockerfile_path:
        description: "The path of the dockerfile to build."
        type: string
        default: "Dockerfile"
      dockerfile_directory:
        description: "The directory to use to build image."
        type: string
        default: "."
      image_name:
        description: "The name of the image."
        type: string
        default: "jobteaser/$CIRCLE_PROJECT_REPONAME"
      image_tag:
        description: "The tag of the image."
        type: string
        default: "git-$CIRCLE_SHA1"
      tag_latest:
        description: "Tag the image with the 'latest' tag."
        type: boolean
        default: false
    steps:
      - run:
          name: "Build the image."
          command: |
            docker build -t <<parameters.image_name>>:<<parameters.image_tag>> \
                         --label org.opencontainers.image.vendor=JobTeaser \
                         --label org.opencontainers.image.url=https://github.com/jobteaser/$CIRCLE_PROJECT_REPONAME \
                         --label org.opencontainers.image.revision=$CIRCLE_SHA1 \
                         -f <<parameters.dockerfile_path>> \
                         <<parameters.dockerfile_directory>>
      - when:
          condition: <<parameters.tag_latest>>
          steps:
            - run:
                name: "Tag latest."
                command: |
                  docker tag <<parameters.image_name>>:<<parameters.image_tag>> \
                             <<parameters.image_name>>:latest

  check_image_trivy:
    parameters:
      image_name:
        description: "The name of the image."
        type: string
        default: "jobteaser/$CIRCLE_PROJECT_REPONAME"
      image_tag:
        description: "The tag of the image."
        type: string
        default: "git-$CIRCLE_SHA1"
    steps:
      - run:
          name: "Check the image with trivy"
          command: |
            trivy --no-progress -f json -o /tmp/trivy.json \
              <<parameters.image_name>>:<<parameters.image_tag>>
      - store_artifacts:
          path: "/tmp/trivy.json"

  push_image:
    parameters:
      image_name:
        description: "The name of the image."
        type: string
        default: "jobteaser/$CIRCLE_PROJECT_REPONAME"
      image_tag:
        description: "The tag of the image."
        type: string
        default: "git-$CIRCLE_SHA1"
    steps:
      - run:
          name: "Push the image to the remote registry."
          command: |
            docker push <<parameters.image_name>>:<<parameters.image_tag>>

jobs:
  build_image:
    parameters:
      dockerfile_path:
        description: "The path of the dockerfile to build."
        type: string
        default: "Dockerfile"
      dockerfile_directory:
        description: "The directory to use to build image."
        type: string
        default: "."
      image_name:
        description: "The name of the Docker image."
        type: string
        default: "jobteaser/$CIRCLE_PROJECT_REPONAME"
      image_tag:
        description: "The tag of the Docker image."
        type: string
        default: "git-$CIRCLE_SHA1"
      tag_latest:
        description: "Tag the image with the 'latest' tag."
        type: boolean
        default: false
    executor: "build"
    steps:
      - checkout
      - setup
      - login
      - build_image:
          dockerfile_path: "<<parameters.dockerfile_path>>"
          dockerfile_directory: "<<parameters.dockerfile_directory>>"
          image_name: "<<parameters.image_name>>"
          image_tag: "<<parameters.image_tag>>"
          tag_latest: <<parameters.tag_latest>>
      - check_image_trivy:
          image_name: "<<parameters.image_name>>"
          image_tag: "<<parameters.image_tag>>"
      - push_image:
          image_name: "<<parameters.image_name>>"
          image_tag: "<<parameters.image_tag>>"
      - when:
          condition: <<parameters.tag_latest>>
          steps:
            - push_image:
                image_name: "<<parameters.image_name>>"
                image_tag: "latest"
