#!/usr/bin/env bash

SLACK_TRANSLATION_NOTIF_URL=$1

#Only report branches old enough (>30min) to have possibly been auto-merged
if [[ $(($(date +%s) - $(git log -1 --format=%ct))) -gt 1800 ]]; then
  MESSAGE=":red_circle: $CIRCLE_BRANCH branch still exists:"

  if [ "$CIRCLE_PULL_REQUEST" = "" ]; then
    MESSAGE="$MESSAGE PR auto-merge have failed because NO PR WAS CREATED.' :red_circle:"
  else
    MESSAGE="$MESSAGE PR auto-merge may have failed for '$CIRCLE_PULL_REQUEST' :red_circle:"
  fi

  curl -X POST -H 'Content-type: application/json' \
       --data "{\"text\": \"$MESSAGE\"}" \
       "$SLACK_TRANSLATION_NOTIF_URL"
fi
