version: 2.1

description: |
  Use Helm in your workflows.

executors:
  deploy:
    docker:
      - image: "jobteaser/circleci-helm-deploy:latest"
        auth:
          username: "$DOCKER_LOGIN"
          password: "$DOCKER_PASSWORD"

commands:
  configure_kubernetes_client:
    description: "Configure the kubernetes client."
    parameters:
      kubernetes_namespace:
        description: "The Kubernetes namespace."
        type: string
        default: "$CIRCLE_PROJECT_REPONAME"
      kubernetes_endpoint:
        description: "The URL of the Kubernetes API endpoint."
        type: string
        default: "$K8S_ENDPOINT"
      kubernetes_ca_cert:
        description: "The CA certificate of the Kubernetes API server."
        type: string
        default: "$K8S_CA_CERT_STAGING"
      kubernetes_user_token:
        description: "The Kubernetes user token."
        type: string
        default: "$K8S_USER_TOKEN_STAGING"
    steps:
      - run:
          name: "Configure the kubernetes client"
          command: |
            echo "<<parameters.kubernetes_ca_cert>>" | base64 -d >/tmp/k8s-ca-cert.pem
            kubectl config set-cluster circleci.cluster \
              --certificate-authority=/tmp/k8s-ca-cert.pem \
              --server=<<parameters.kubernetes_endpoint>>
            kubectl config set-context circleci.context \
              --cluster=circleci.cluster
            kubectl config set-credentials circleci \
              --token=<<parameters.kubernetes_user_token>>
            kubectl config set-context circleci.context \
              --user=circleci \
              --namespace=<<parameters.kubernetes_namespace>>
            kubectl config use-context circleci.context

  check_helm_chart:
    description: "Check the Helm chart using the Helm linter."
    parameters:
      helm_chart_path:
        description: "The path of the Helm chart."
        type: string
        default: "./k8s/$CIRCLE_PROJECT_REPONAME"
      helm_value_file_path:
        description: "The path of the extra value file to apply."
        type: string
        default: "./k8s/$CIRCLE_PROJECT_REPONAME/$HELM_VALUE_FILE_NAME"
    steps:
      - run:
          name: "Check the Helm chart"
          command: |
            helm lint \
              -f <<parameters.helm_value_file_path>> \
              --set=circleci.sha1=$CIRCLE_SHA1 \
              --set=circleci.branch=$CIRCLE_BRANCH \
              <<parameters.helm_chart_path>>

  expand_helm_templates:
    description: "Expand and store Helm templates as artifacts."
    parameters:
      environment:
        description: "The runtime environment."
        type: string
        default: "prod"
      helm_chart_path:
        description: "The path of the Helm chart."
        type: string
        default: "./k8s/$CIRCLE_PROJECT_REPONAME"
      helm_value_file_path:
        description: "The path of the extra value file to apply."
        type: string
        default: "./k8s/$CIRCLE_PROJECT_REPONAME/$HELM_VALUE_FILE_NAME"
      helm_release_name:
        description: "The Helm release name."
        type: string
        default: "$CIRCLE_PROJECT_REPONAME-$CIRCLE_BRANCH"
    steps:
      - run:
          name: "Expand Helm templates"
          command: |
            mkdir -p /tmp/helm-templates/<<parameters.environment>>
            helm template \
              -n <<parameters.helm_release_name>> \
              -f <<parameters.helm_value_file_path>> \
              --set=circleci.sha1=$CIRCLE_SHA1 \
              --set=circleci.branch=$CIRCLE_BRANCH \
              --output-dir /tmp/helm-templates/<<parameters.environment>> \
              <<parameters.helm_chart_path>>
      - store_artifacts:
          path: "/tmp/helm-templates/<<parameters.environment>>"

  tag_deployment:
    parameters:
      environment:
        description: "The runtime environment."
        type: string
        default: "prod"
    steps:
      - run:
          name: "Configure Git"
          command: |
            git config --global user.email "dev@jobteaser.com"
            git config --global user.name "Jobtomate CircleCI"
      - run:
          name: "Tag the deployment"
          command: |
            tag="deployment-<<parameters.environment>>-$(date -u +'%Y%m%d%H%M%S%N')"
            git tag $tag
            git push origin $tag

jobs:
  push:
    parameters:
      helm_repo_url:
        description: "Helm repository URL"
        default: "$HELM_REPO_URL"
        type: string
      helm_repo_user:
        description: "Helm repository username"
        default: "$HELM_REPO_USER"
        type: string
      helm_repo_pass:
        description: "Helm repository password"
        default: "$HELM_REPO_PASS"
        type: string
      helm_chart_path:
        description: "The path of the Helm chart."
        type: string
        default: "./k8s/$CIRCLE_PROJECT_REPONAME"
    executor: "deploy"
    steps:
      - checkout
      - run:
          name: "Push Helm chart to remote repo"
          command: |
            cd <<parameters.helm_chart_path>>
            helm init --client-only
            helm plugin install https://github.com/chartmuseum/helm-push
            helm repo add --username <<parameters.helm_repo_user>> --password <<parameters.helm_repo_pass>> jobteaser-private <<parameters.helm_repo_url>>
            helm repo add jobteaser-public https://jobteaser.github.io/charts
            helm repo update
            helm dep update
            helm push . jobteaser-private
  deploy:
    parameters:
      environment:
        description: "The runtime environment."
        type: string
        default: "prod"
      docker_image:
        description: "The docker image to deploy."
        type: string
        default: "jobteaser/$CIRCLE_PROJECT_REPONAME"
      docker_tag:
        description: "The tag of the docker image to deploy."
        type: string
        default: "git-$CIRCLE_SHA1"
      kubernetes_namespace:
        description: "The Kubernetes namespace."
        type: string
        default: "$CIRCLE_PROJECT_REPONAME"
      kubernetes_endpoint:
        description: "The URL of the Kubernetes API endpoint."
        type: string
        default: "$K8S_ENDPOINT"
      kubernetes_ca_cert:
        description: "The CA certificate of the Kubernetes API server."
        type: string
        default: "$K8S_CA_CERT_STAGING"
      kubernetes_user_token:
        description: "The Kubernetes user token."
        type: string
        default: "$K8S_USER_TOKEN_STAGING"
      helm_chart_path:
        description: "The path of the Helm chart."
        type: string
        default: "./k8s/$CIRCLE_PROJECT_REPONAME"
      helm_release_name:
        description: "The Helm release name."
        type: string
        default: "$CIRCLE_PROJECT_REPONAME-$CIRCLE_BRANCH"
      helm_wait_for_ready:
        description: "Whether or not to wait for the pods being actually ready."
        type: boolean
        default: true
      helm_upgrade_timeout:
        description: "The amount of time to wait for the Helm release upgrade to finish in seconds."
        type: integer
        default: 300
      helm_value_file_path:
        description: "The path of the extra value file to apply."
        type: string
        default: "./k8s/$CIRCLE_PROJECT_REPONAME/$HELM_VALUE_FILE_NAME"
      check_helm_chart:
        description: "Whether to check the Helm configuration or not."
        type: boolean
        default: true
      tag_deployment:
        description: "Whether to create a deployment Git tag or not."
        type: boolean
        default: false
    executor: "deploy"
    steps:
      - run:
          name: "Wait for all other builds to complete"
          command: |
            circle-wait-job
      - checkout
      - run:
          name: "Ensure that this build is more recent than the last deployed one"
          command: |
            deployable -p "deployment-<<parameters.environment>>-*"
      - configure_kubernetes_client:
          kubernetes_ca_cert: "<<parameters.kubernetes_ca_cert>>"
          kubernetes_endpoint: "<<parameters.kubernetes_endpoint>>"
          kubernetes_user_token: "<<parameters.kubernetes_user_token>>"
          kubernetes_namespace:  "<<parameters.kubernetes_namespace>>"
      - run:
          name: "Initialize Helm"
          command: |
            cd <<parameters.helm_chart_path>>
            helm init --client-only
            helm repo add jobteaser https://jobteaser.github.io/charts
            helm dep update
      - when:
          condition: <<parameters.check_helm_chart>>
          steps:
            - check_helm_chart:
                helm_chart_path: "<<parameters.helm_chart_path>>"
                helm_value_file_path: "<<parameters.helm_value_file_path>>"
      - expand_helm_templates:
          environment: "<<parameters.environment>>"
          helm_chart_path: "<<parameters.helm_chart_path>>"
          helm_release_name: "<<parameters.helm_release_name>>"
          helm_value_file_path: "<<parameters.helm_value_file_path>>"
      - run:
          name: "Install or upgrade the Helm release"
          command: |
            helm upgrade \
              --tiller-namespace=<<parameters.kubernetes_namespace>> \
              --namespace=<<parameters.kubernetes_namespace>> \
              -f <<parameters.helm_value_file_path>> \
              --set=circleci.sha1=$CIRCLE_SHA1 \
              --set=circleci.branch=$CIRCLE_BRANCH \
              --set=image=<<parameters.docker_image>>:<<parameters.docker_tag>> \
              --wait=<<parameters.helm_wait_for_ready>> \
              --timeout=<<parameters.helm_upgrade_timeout>> \
              --install <<parameters.helm_release_name>> <<parameters.helm_chart_path>>
      - when:
          condition: <<parameters.tag_deployment>>
          steps:
            - tag_deployment:
                environment: "<<parameters.environment>>"
