version: 2.1

commands:
  prepare:
    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt-get update -y
            apt-get install -y make curl git
      - run:
          name: "Install the CircleCI command line program"
          command: |
            curl -fLSs https://circle.ci/cli | bash
            circleci update

jobs:
  validate:
    docker:
      - image: "ubuntu:18.04"
    steps:
      - prepare
      - checkout
      - run:
          name: "Validate orbs"
          command: |
            make validate

  publish_dev:
    docker:
      - image: "ubuntu:18.04"
    steps:
      - prepare
      - checkout
      - run:
          name: "Publish development orbs"
          command: |
            make publish-dev

  publish_stable:
    docker:
      - image: "ubuntu:18.04"
    steps:
      - prepare
      - checkout
      - run:
          name: "Publish stable orbs"
          command: |
            make publish-stable

workflows:
  main:
    jobs:
      - validate
      - publish_dev:
          requires: ["validate"]
          filters:
            branches:
              only: ["master"]
      - publish_stable:
          requires: ["validate"]
          filters:
            branches:
              ignore: "/.*/"
            tags:
              only: "/^v.*/"

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                ["master"]
    jobs:
      - validate
      - publish_dev:
          requires: ["validate"]
