version: 2.1

jobs:
  build_and_publish:
    docker:
      - image: "ubuntu:18.04"

    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt-get update -y
            apt-get install -y make curl git
      - run:
          name: "Install the CircleCI command line program"
          command: |
            curl -fLSs https://circle.ci/cli | bash
            circleci update
      - checkout
      - run:
          name: "Validate orbs"
          command: |
            make validate
      - run:
          name: "Publish development orbs"
          command: |
            make publish-dev
      - run:
          name: "Publish stable orbs"
          filters:
            branches:
              ignore: "/.*/"
            tags:
              only: "/^v.*/"
          command: |
            make publish-stable

workflows:
  main:
    jobs:
      - build_and_publish

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                ["master"]
    jobs:
      - build_and_publish
