version: 2.1

jobs:
  build:
    docker:
      - image: "ubuntu:18.04"

    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt-get update -y
            apt-get install -y make curl
      - run:
          name: "Install the CircleCI command line program"
          command: |
            curl -fLSs https://circle.ci/cli | bash
            circleci update
      - checkout
      - run:
          name: "Validate orbs"
          command: |
            make validate
      - run:
          name: "Publish development orbs"
          command: |
            make publish-dev
