version: 2.1

description: |
  Standard jobs for services using the rb-service Ruby module.

orbs:
  service: "jobteaser/service@dev:master"
  docker: "jobteaser/docker@dev:master"

executors:
  ci:
    docker:
      - image: "jobteaser/rb-service-ci:latest"
        auth:
          username: "$DOCKER_LOGIN"
          password: "$DOCKER_PASSWORD"

commands:
  save_ruby_bundle_cache:
    steps:
      - save_cache:
          key: $CIRCLE_PROJECT_REPONAME-{{ .Branch }}-{{ checksum "Gemfile.lock" }}-v1
          paths:
            - "/vendor/bundle"
            - "/vendor/cache"

  restore_ruby_bundle_cache:
    steps:
      - restore_cache:
          keys:
            - $CIRCLE_PROJECT_REPONAME-{{ .Branch }}-{{ checksum "Gemfile.lock" }}-v1

jobs:
  test:
    parameters:
      executor:
        description: "The executor to use for the job."
        type: "executor"
        default: "ci"
    executor: "<<parameters.executor>>"
    steps:
      - service/configure_ssh
      - checkout
      - restore_ruby_bundle_cache
      - run:
          name: "Install dependencies"
          command: |
            bundle install \
              --deployment \
              --retry=3 \
              --no-color
      - run:
          name: "Run tests"
          command: |
            bundle exec rake test
      - save_ruby_bundle_cache

  build:
    parameters:
      executor:
        description: "The executor to use for the job."
        type: "executor"
        default: "ci"
    executor: "<<parameters.executor>>"
    steps:
      - service/configure_ssh
      - checkout
      - restore_ruby_bundle_cache
      - run:
          name: "Package dependencies"
          command: |
            bundle package --all --all-platforms
      - save_ruby_bundle_cache
      - docker/setup
      - docker/login
      - docker/build_image
      - docker/push_image
