version: 2.1

description: |
  Standard jobs for services using the go-service Go module.

orbs:
  service: "jobteaser/service@dev:master"
  docker: "jobteaser/docker@dev:feat-add-docker-tags"

executors:
  ci:
    # We should avoid using latest image tag.
    # Prefer using specific tag to avoid breaking your CI when a breaking change in the image occurs.
    docker:
      - image: "jobteaser/go-service-ci:<<parameters.tag>>"
        auth:
          username: "$DOCKER_LOGIN"
          password: "$DOCKER_PASSWORD"
    parameters:
      tag:
        default: 'latest'
        description: >
          Pick a specific jobteaser/go-service-ci image version tag
        type: string

commands:
  save_go_pkg_cache:
    steps:
      - save_cache:
          key: $CIRCLE_PROJECT_REPONAME-v2-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg"

  restore_go_pkg_cache:
    steps:
      - restore_cache:
          keys:
            - $CIRCLE_PROJECT_REPONAME-v2-{{ .Branch }}-{{ checksum "go.sum" }}
            - $CIRCLE_PROJECT_REPONAME-v2-{{ .Branch }}
            - $CIRCLE_PROJECT_REPONAME-v2-

jobs:
  test:
    parameters:
      executor:
        description: "The executor to use for the job."
        type: "executor"
        default: "ci"
      pre_test_command:
        description: "A shell command to execute before running the test suite."
        type: "string"
        default: "true"
    executor: "<<parameters.executor>>"
    steps:
      - service/configure_ssh
      - service/configure_git
      - checkout
      - restore_go_pkg_cache
      - run:
          name: "Run static analysis"
          command: |
            make vet
      - run:
          name: "Run tests"
          command: |
            <<parameters.pre_test_command>>
            make test
      - save_go_pkg_cache

  build:
    parameters:
      executor:
        description: "The executor to use for the job."
        type: "executor"
        default: "ci"
    executor: "<<parameters.executor>>"
    steps:
      - service/configure_ssh
      - service/configure_git
      - checkout
      - restore_go_pkg_cache
      - run:
          name: "Build the project"
          command: |
            make build
      - save_go_pkg_cache
      - service/generate_build_info
      - store_artifacts:
          path: "./bin"
      - store_artifacts:
          path: "./cfg"
      - store_artifacts:
          path: "./data"
      - docker/setup
      - docker/login
      - docker/build_image
      - docker/check_image_trivy
      - docker/push_image
