version: 2.1

description: |
  Standard jobs for services using the go-service Go module.

orbs:
  docker: "jobteaser/docker@dev:master"

executors:
  ci:
    docker:
      - image: "jobteaser/go-service-ci:latest"
        auth:
          username: "$DOCKER_LOGIN"
          password: "$DOCKER_PASSWORD"

commands:
  configure_ssh:
    steps:
      - run:
          name: "Configure SSH"
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com > ~/.ssh/known_hosts

  configure_git:
    steps:
      - run:
          name: "Configure Git"
          command: |
            git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"

  save_go_pkg_cache:
    steps:
      - save_cache:
          key: $CIRCLE_PROJECT_REPONAME-{{ .Branch }}-{{ checksum "go.sum" }}-v1
          paths:
            - "/go/pkg"

  restore_go_pkg_cache:
    steps:
      - restore_cache:
          keys:
            - $CIRCLE_PROJECT_REPONAME-{{ .Branch }}-{{ checksum "go.sum" }}-v1

  generate_build_info:
    parameters:
      file_path:
        description: "The path of the file to generate."
        type: "string"
        default: "./data/build.json"
    steps:
      - run:
          name: "Generate the build info file"
          command: |
            echo '{"gitHash": "$CIRCLE_SHA1"}' >"<<parameters.file_path>>"

jobs:
  test:
    parameters:
      executor:
        description: "The executor to use for the job."
        type: "executor"
        default: "ci"
    executor: "<<parameters.executor>>"
    steps:
      - configure_ssh
      - configure_git
      - checkout
      - restore_go_pkg_cache
      - run:
          name: "Run static analysis"
          command: |
            make vet
      - run:
          name: "Run tests"
          command: |
            make test
      - save_go_pkg_cache

  build:
    parameters:
      executor:
        description: "The executor to use for the job."
        type: "executor"
        default: "ci"
    executor: "<<parameters.executor>>"
    steps:
      - configure_ssh
      - configure_git
      - checkout
      - restore_go_pkg_cache
      - run:
          name: "Build the project"
          command: |
            make build
      - save_go_pkg_cache
      - generate_build_info
      - store_artifacts:
          path: "./bin"
      - store_artifacts:
          path: "./cfg"
      - store_artifacts:
          path: "./data"
      - docker/setup
      - docker/login
      - docker/build_image
      - docker/push_image
