version: 2.1

description: |
  Create and announce changelogs for Git repositories.

executors:
  default:
    docker:
      - image: "ubuntu:18.04"

jobs:
  publish:
    parameters:
      environment:
        description: "The runtime environment."
        type: string
        default: "staging"
      slack_webhook_uri:
        description: "The Slack webhook URI."
        type: string
        default: "$SLACK_WEBHOOK_URI"
      icon_emoji:
        description: "The emoji to use as icon for messages."
        type: string
        default: ":poop:"
    executor: "default"
    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt-get update -y
            apt-get install -y git openssh-client ca-certificates curl jq
            curl -sL https://deb.nodesource.com/setup_10.x | bash -
            apt-get install -y nodejs
      - checkout
      - run:
          name: "Publish the changelog"
          command: |
            # Note that we need to tag just before the last one since we just
            # tagged the new version.
            changelog=$(npx generate_slack_release_notes https://github.com/jobteaser/$CIRCLE_PROJECT_REPONAME deployment-<<parameters.environment>>-)
            message="Deployment finished for *$CIRCLE_PROJECT_REPONAME* in *<<parameters.environment>>*:"$'\n'
            message=$(jq -n --arg msg "$message" '$msg')
            icon_emoji=$(jq -n --arg s "<<parameters.icon_emoji>>" '$s')
            curl -X POST \
                 -H 'Content-Type: application/json' \
                 --data "{\"username\": \"CircleCI\", \"text\": $message, \"icon_emoji\": $icon_emoji}" \
                 <<parameters.slack_webhook_uri>>
