version: 2.1

description: |
  Create and announce changelogs for Git repositories.

executors:
  default:
    docker:
      - image: "jobteaser/circleci-changelog-publish:1.0.0"
        auth:
          username: "$DOCKER_LOGIN"
          password: "$DOCKER_PASSWORD"

jobs:
  publish:
    parameters:
      environment:
        description: "The runtime environment."
        type: string
        default: "staging"
      slack_webhook_uri:
        description: "The Slack webhook URI."
        type: string
        default: "$SLACK_WEBHOOK_URI"
      icon_emoji:
        description: "The emoji to use as icon for messages."
        type: string
        default: ":poop:"
    executor: "default"
    steps:
      - checkout
      - run:
          name: "Publish the changelog"
          command: |
            # Note that we need to tag just before the last one since we just
            # tagged the new version.
            npx @jobteaser/slack-release-notes \
                --repo-url "https://github.com/jobteaser/$CIRCLE_PROJECT_REPONAME" \
                --tag-prefix "deployment-<<parameters.environment>>-" \
                --project-name "$CIRCLE_PROJECT_REPONAME" \
                --webhook-url "<<parameters.slack_webhook_uri>>" \
                --icon-emoji "<<parameters.icon_emoji>>"
