#!/usr/bin/env sh

set -eu

tag=$(git describe --tags --always --dirty)

if [ -z $(echo "$tag" | egrep "^v[0-9]+\.[0-9]+\.[0-9]+$") ]; then
    echo "repository is not a clean tagged stable version" >/dev/stderr
    exit 1
fi

version=${tag#v}

for orb; do
    orb_name=$(dirname ${orb#orbs/})
    orb_ref=jobteaser/$orb_name@$version

    echo circleci orb publish $orb $orb_ref
done
