#!/usr/bin/env sh

set -eu

git_branch=$(git rev-parse --abbrev-ref HEAD)
version="dev:$git_branch"

for orb; do
    orb_name=$(dirname ${orb#orbs/})
    orb_ref=jobteaser/$orb_name@$version

    echo circleci orb publish $orb $orb_ref
done
