#!/usr/bin/env ruby

require("optparse")
require("net/http")
require("json")
require("date")

class CLI
  attr_reader(:token, :organization, :project, :job, :current_job, :branch, :interval, :vcs, :build_number)

  def initialize
    @branch = ENV["CIRCLE_BRANCH"]
    # interval is specified in seconds
    @interval = "60"
    @vcs = "github"
    @build_number = ENV["CIRCLE_BUILD_NUM"]
    @token = ENV["CIRCLE_TOKEN"]
    @current_job = ENV["CIRCLE_JOB"]
    @job = ENV["CIRCLE_JOB"]
    @organization = ENV["CIRCLE_PROJECT_USERNAME"]
    @project = ENV["CIRCLE_PROJECT_REPONAME"]
  end

  def parse(args)
    OptionParser.new do |parser|
      define_options!(parser)
      parser.parse!(args)
    end

    must_not_empty("branch", @branch)
    must_not_empty("interval", @interval)
    must_not_empty("vcs", @vcs)
    must_not_empty("current-build-number", @build_number)
    must_not_empty("token", @token)
    must_not_empty("job", @job)
    must_not_empty("current_job", @current_job)
    must_not_empty("organization", @organization)
    must_not_empty("project", @project)

    self
  end

  private

  def must_not_empty(key, value)
    if value.to_s.empty?
      raise(ArgumentError, "the #{key} is missing or empty")
    end
  end

  def define_options!(parser)
    parser.banner = "Usage: circleci-wait-job OPTIONS"
    parser.separator("")
    parser.separator("OPTIONS")
    parser.separator("")

    parser.on("-t=VALUE", "--token=VALUE", "the circleci api token") { |value| @token = value }
    parser.on("-o=VALUE", "--organization=VALUE", "the circleci organization name") { |value| @organization = value }
    parser.on("-p=VALUE", "--project=VALUE", "the circleci project name") { |value| @project = value }
    parser.on("-j=VALUE", "--job=VALUE", "the circleci job name") { |value| @job = value }
    parser.on("-c=VALUE", "--current_job=VALUE", "the circleci currently running job name") { |value| @current_job = value }
    parser.on("-b=VALUE", "--branch=VALUE", "the circleci branch") { |value| @branch = value }
    parser.on("-i=VALUE", "--interval=VALUE", "the wait time between pooling") { |value| @interval = value }
    parser.on("--vcs=VALUE", "the version control system (default: github)") { |value| @vcs = value }
    parser.on("--current-build-number=VALUE", "the current circleci build number") { |value| @build_number = value }

    parser.on_tail("-h", "--help", "print help and exit") do
      puts(parser)
      exit(0)
    end

    parser.on_tail("--version", "print version and exit") do
      puts("v0.0.1")
      exit(0)
    end
  end
end

cli = CLI.new

begin
  options = cli.parse(ARGV)
rescue ArgumentError => e
  puts(e.message)
  exit(1)
end

uri_for_running = URI::HTTPS.build(host: "circleci.com",
                       path: File.join("/",
                                       "api",
                                       "v1.1",
                                       "project",
                                       options.vcs.to_s,
                                       options.organization.to_s,
                                       options.project.to_s,
                                       "tree",
                                       options.branch.to_s),
                       query: URI.encode_www_form({"circle-token" => options.token.to_s,
                                                   "shallow" => true,
                                                   "filter" => "running"}))

uri_for_successful = URI::HTTPS.build(host: "circleci.com",
                       path: File.join("/",
                                       "api",
                                       "v1.1",
                                       "project",
                                       options.vcs.to_s,
                                       options.organization.to_s,
                                       options.project.to_s,
                                       "tree",
                                       options.branch.to_s),
                       query: URI.encode_www_form({"circle-token" => options.token.to_s,
                                                   "shallow" => true,
                                                   "filter" => "successful"}))


def other_job_is_running?(uri_for_running, uri_for_successful, targeted_job, current_job, current_build_num)
  response = Net::HTTP.get(uri_for_running)
  running_builds = JSON.parse(response)

  # Check if another targeted job (most likely a production deployment job) is already running.
  has_concurrent_job = builds.any? do |build|
    build.dig("workflows", "job_name").to_s == targeted_job
  end

  if has_concurrent_job
    puts "A build is already running the job #{targeted_job}."
    return true
  else
    puts "No build running job #{targeted_job} were found."
    puts "\nChecking that no other builds are currently running job #{current_job}..."
    # We know that no "production deployment job" is running but there is a possibility that 2 builds are
    # running the same job as the current one simultaneously. This means that both builds could enter a
    # "production deployment job" at the same time after the present job is done. We must avoid it.
    # Check if another other build is running the same job as the current one (most likely a
    # concurrent_build_management job).
    # Iterate on builds and regroup builds by job name in a dict:
    # Ex: { concurrent_build_management: [build1, build2], test_js: [build3], ...}
    concurrent_builds_for_current_job = builds.select do |build|
      build.dig("workflows", "job_name").to_s == current_job
    end

    unless concurrent_builds_for_current_job.any?
      puts "No builds running job #{current_job} were found."
      return false
    end

    puts "\nChecking which concurrent build is the oldest (based on committer_date)..."

    # Find build for the oldest code
    oldestBuild = concurrent_builds_for_current_job.min do |build1, build2|
      DateTime.parse(build1["committer_date"]) <=> DateTime.parse(build2["committer_date"])
    end

    puts "Oldest build is #{oldestBuild["build_num"]}"

    if current_build_num != oldestBuild["build_num"]
      puts "\nCurrent build has code more recent that another one running, it must wait"
      return true
    end

    puts "\nCurrent build has the oldest code, it can continue running"

    # There is generally around 4 seconds between a job being successful and the following job being running.
    # It means it is possible that an older job similar to the current job just successful and that
    # the associate targeted job has not started yet.
    # In this case, two target jobs would run concurrently.
    # To avoid this edge case, we ensure that no jobs similar to the current job successful a few seconds ago.
    response = Net::HTTP.get(uri_for_successful)
    successful_builds = JSON.parse(response)
    few_seconds_ago = Time.now - 30 # observed latency are up to 10 seconds.

    puts "\nChecking if a build has successfully runned #{current_job} few seconds ago..."
    may_have_concurrent_job = successful_builds.any? do |build|
      build.dig("workflows", "job_name").to_s == current_job && DateTime.parse(build["stop_time"]) > few_seconds_ago
    end

    if may_have_concurrent_job
      puts "A build has successfully runned #{current_job} few seconds ago."
      puts "Another build may start #{targeted_job} in few seconds."
      return true
    else
      puts "No builds successfully runned job #{current_job} few seconds ago."
      return false
    end
  end
end

puts("Check no other #{options.job} for #{options.branch} branch is running.")

while other_job_is_running?(uri_for_running, uri_for_successful, options.job.to_s, options.current_job.to_s, options.build_number.to_i) do
  puts("Another #{options.job} for #{options.branch} branch already running, check again in #{options.interval} seconds.\n")
  sleep(options.interval.to_i)
end
